arb-dir: lib/l10n
template-arb-file: app_en.arb

# Put the generated Dart file in your repo (not a synthetic package)
synthetic-package: false
output-dir: lib/l10n/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations

# Optional niceties:
nullable-getter: false
use-deferred-loading: false
