import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

// ✅ Import the generated localizations from YOUR repo (matches l10n.yaml output-dir)
import 'l10n/generated/app_localizations.dart';

import 'pages/auth_gate_page.dart';
import 'pages/splash_loader_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await setupFCM();
  runApp(const ChoreBidApp());
}

Future<void> setupFCM() async {
  final messaging = FirebaseMessaging.instance;

  // Request permission (iOS only)
  await messaging.requestPermission();

  // Get token
  final token = await messaging.getToken();
  // ignore: avoid_print
  print('FCM Token: $token');

  if (token != null) {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid != null) {
      // Save token to Firestore
      await FirebaseFirestore.instance.collection('users').doc(uid).update({
        'fcmToken': token,
      });
    }
  }

  // Handle foreground messages
  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    // ignore: avoid_print
    print('Foreground message: ${message.notification?.title}');
  });
}

class ChoreBidApp extends StatelessWidget {
  const ChoreBidApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Optional static fallback; runtime title comes from ARB below
      title: 'ChoreBid',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.indigo),

      // ✅ Localization wiring (generated by gen_l10n)
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,

      // ✅ Title from ARB (e.g., "ChoreBid" / "צ'ורביד")
      onGenerateTitle: (context) => AppLocalizations.of(context)!.appTitle,

      // If you want to force Hebrew during testing, uncomment:
      // locale: const Locale('he'),

      initialRoute: '/',
      routes: {
        '/': (context) => const AuthGatePage(),
        '/splash': (context) => const SplashLoaderPage(),
      },
    );
  }
}
